# https://blog.deniger.net/post/gitlab-maven-optimize-build/
# https://forum.gitlab.com/t/getting-mvn-release-to-work-with-gitlab-ci/4904/2
# https://crypt.codemancers.com/posts/2021-08-31-release-artifacts-using-gitlab-cicd/

# latest: maven:latest
image: maven:3.6.3-jdk-8

# stages
stages:
  - build
  - test
  - prepare
  - release

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

prepareRelease:
  stage: prepare
  tags:
    # runner tags
    - docker
  script:
    # install ssh agent if ssh agent is not installed
    - '(which ssh-agent) || ( apt-get update -y && apt-get install openssh-client -y )'
    # run ssh agent
    - eval $(ssh-agent -s)
    # add the ssh key stored in the SSH_PRIVATE_KEY variable to the ssh agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    # disable host key check
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config user.name "jeeto jeeto"
    - git config user.email "jeeto.jeeto@gmail.com"
    # detached HEAD is checked out
    # check out branch in the CI_BUILD_REF_NAME variable
    - git checkout -B "$CI_BUILD_REF_NAME"
    - mvn $MAVEN_CLI_OPTS release:prepare
    - echo $CI_JOB_ID
    - echo RELEASE_JOB_ID=$CI_JOB_ID >> release.env
    - releaseVersion=`awk -F "[><]" '/releaseVersion/{print $3}' pom.xml`
    - echo $releaseVersion
    - echo RELEASE_VERSION=$releaseVersion >> release.env
    - mkdir release
    - mv app/target/oboco-${releaseVersion}.zip release/oboco-${releaseVersion}.zip
  artifacts:
    paths:
      - release/
    reports:
      dotenv: release.env
  when: manual
  only:
     - master

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo $RELEASE_JOB_ID
    - echo $RELEASE_VERSION
  needs:
    - job: prepareRelease
      artifacts: true
  release:
    name: "oboco-${RELEASE_VERSION}"
    description: "oboco-${RELEASE_VERSION}"
    tag_name: "oboco-${RELEASE_VERSION}"
    assets:
      links:
        - name: "oboco-${RELEASE_VERSION}"
          url: "https://gitlab.com/jeeto/oboco/-/jobs/${RELEASE_JOB_ID}/artifacts/file/release/oboco-${RELEASE_VERSION}.zip"
  only:
    - master