#https://blog.deniger.net/post/gitlab-maven-optimize-build/

# latest: maven:latest
image: maven:3.3.9-jdk-8

# stages
stages:
  - build
  - test
  - package

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  # cache repository
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# share dependencies
cache:
  paths:
    # cache repository
    - .m2/repository/

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
  # share artifacts
  artifacts:
    expire_in: 1 hour
    paths: 
      - target/
      # for modules
      # use " and not / at the end...
      - "*/target"

test:
  stage: test
  script:
    # every stage does a new 'git clone'
    # the java files are more recent than the class files
    # make the class files more recent with touch
    # otherwise maven will recompile the java files
    - find . -name "*.class" -exec touch {} \+
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: package
  script:
    # see: test
    - find . -name "*.class" -exec touch {} \+
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
  artifacts:
    expire_in: 1 hour
    paths:
      - app/target/oboco-*.zip