image: maven:latest

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

cache:
  paths:
    - .m2/repository/

compile:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

package:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
  artifacts:
    paths:
      - app/target/oboco-*.zip

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test